services:
  prometheus:
    image: prom/prometheus:v3.0.1
    volumes:
      - ./dev/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:11.4.0
    volumes:
      - ./dev/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
volumes:
  prometheus:
