[package]
name = "ayaya-runner-shuttle"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-runtime = { workspace = true }
anyhow = { version = "1" }
miette = { workspace = true }
ayaya-lib = { path = "../ayaya-lib" }
