[package]
name = "ayaya-runner-shuttle"
version = "0.1.0"
edition = "2021"

[dependencies]
# workspace deps
shuttle-runtime = { workspace = true }
miette = { workspace = true }

anyhow = { version = "1" }
ayaya-lib = { path = "../ayaya-lib" }
