//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ban_shit_music")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ban_id: Uuid,
    pub server_id: i64,
    pub title: String,
    pub artist: String,
    pub youtube_id: String,
    pub ban_start: TimeDateTimeWithTimeZone,
    pub ban_end: TimeDateTimeWithTimeZone,
    pub ban_duration: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
