#![cfg_attr(coverage_nightly, coverage(off))]
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod ban_shit_music;
pub mod ban_user_command_use;
pub mod command_allow_user;
pub mod command_call_log;
pub mod require_category_role;
pub mod require_command_role;
pub mod song_queues;
pub mod sounds;
pub mod upload_noticed;
pub mod user_command_all_time_statistics;
pub mod user_play_queries;
pub mod youtube_cookies;
