//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::song_queues::Entity as SongQueues;
pub use super::sounds::Entity as Sounds;
pub use super::upload_noticed::Entity as UploadNoticed;
pub use super::user_play_queries::Entity as UserPlayQueries;
