//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sounds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sound_id: Uuid,
    pub user_id: i64,
    pub uploaded_server_id: i64,
    pub sound_name: String,
    pub public: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
