//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wuwa_import_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub wuwa_user_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub pool_id: String,
    pub last_time: TimeDateTimeWithTimeZone,
    pub count_at_time: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wuwa_user::Entity",
        from = "Column::WuwaUserId",
        to = "super::wuwa_user::Column::WuwaUserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WuwaUser,
}

impl Related<super::wuwa_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WuwaUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
