//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dashboard_allowlist")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
    pub added_by: i64,
    pub added_at: TimeDateTimeWithTimeZone,
    pub notes: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dashboard_tokens::Entity")]
    DashboardTokens,
}

impl Related<super::dashboard_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DashboardTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
