//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dashboard_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub token_id: Uuid,
    pub user_id: i64,
    pub token_hash: String,
    pub description: String,
    pub created_at: TimeDateTimeWithTimeZone,
    pub last_used_at: Option<TimeDateTimeWithTimeZone>,
    pub expires_at: Option<TimeDateTimeWithTimeZone>,
    pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dashboard_allowlist::Entity",
        from = "Column::UserId",
        to = "super::dashboard_allowlist::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DashboardAllowlist,
}

impl Related<super::dashboard_allowlist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DashboardAllowlist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
