//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "voice_state_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: Uuid,
    pub guild_id: i64,
    pub user_id: i64,
    pub event_kind: String,
    pub from_channel_id: Option<i64>,
    pub to_channel_id: Option<i64>,
    pub occurred_at: TimeDateTimeWithTimeZone,
    pub session_id: Option<Uuid>,
    pub self_mute: bool,
    pub self_deaf: bool,
    pub mute: bool,
    pub deaf: bool,
    pub self_stream: bool,
    pub self_video: bool,
    pub suppress: bool,
    pub request_to_speak_at: Option<TimeDateTimeWithTimeZone>,
    pub raw_state_json: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::voice_sessions::Entity",
        from = "Column::SessionId",
        to = "super::voice_sessions::Column::SessionId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    VoiceSession,
}

impl Related<super::voice_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VoiceSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
