//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "voice_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub session_id: Uuid,
    pub guild_id: i64,
    pub user_id: i64,
    pub channel_id: i64,
    pub joined_at: TimeDateTimeWithTimeZone,
    pub start_is_estimated: bool,
    pub left_at: Option<TimeDateTimeWithTimeZone>,
    pub join_event_id: Option<Uuid>,
    pub leave_event_id: Option<Uuid>,
    pub ended_reason: Option<String>,
    pub join_state_json: Option<String>,
    pub leave_state_json: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::voice_state_events::Entity")]
    VoiceStateEvents,
}

impl Related<super::voice_state_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VoiceStateEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
