//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wuwa_pull")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub wuwa_user_id: i32,
    pub pull_type: i32,
    pub resource_id: i32,
    pub quality_level: i32,
    pub count: i32,
    pub time: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wuwa_resource::Entity",
        from = "Column::ResourceId",
        to = "super::wuwa_resource::Column::ResourceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WuwaResource,
    #[sea_orm(
        belongs_to = "super::wuwa_user::Entity",
        from = "Column::WuwaUserId",
        to = "super::wuwa_user::Column::WuwaUserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WuwaUser,
}

impl Related<super::wuwa_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WuwaResource.def()
    }
}

impl Related<super::wuwa_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WuwaUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
