//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wuwa_resource")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub resource_id: i32,
    #[sea_orm(unique)]
    pub resource_name: String,
    pub resource_type: String,
    pub resource_portrait_path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::wuwa_pull::Entity")]
    WuwaPull,
}

impl Related<super::wuwa_pull::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WuwaPull.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
