//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "youtube_cookies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub entry_id: i32,
    pub date: TimeDateTimeWithTimeZone,
    #[sea_orm(column_type = "Blob")]
    pub cookies: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
