[package]
name = "entity-sqlite"
version = { workspace = true }
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
bincode = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }
