[package]
name = "ayaya-runner-local"
version = { workspace = true }
edition = "2021"

[dependencies]
# workspace deps
miette = { workspace = true }
tokio = { workspace = true }

dotenvy = { version = "0.15" }
ayaya-lib = { path = "../ayaya-lib" }
