//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ban_shit_music")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub ban_id: Vec<u8>,
    pub server_id: u64,
    pub title: String,
    pub artist: String,
    pub youtube_id: String,
    pub ban_start: TimeDateTime,
    pub ban_end: TimeDateTime,
    pub ban_duration: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
